### ISSUE TITLE
'items.b' not found when running itempersonMap()

### ISSUE THREAD

**Issue by rameliaz** [masurp/ggmirt#5]
Hello,

I was running `itempersonMap()` for a graded response model, and got this following error.

> Error in `mutate()`:
> ℹ In argument: `items = forcats::fct_reorder(items, items.b)`.
> Caused by error in `stopifnot()`:
> ! object 'items.b' not found

...and after running `rlang::last_trace()` I got this...

> Backtrace:
>      ▆
>   1. ├─ggmirt::summaryPlot(results.grm, adj_factor = 1.75)
>   2. │ └─ggmirt::itemDist(...)
>   3. │   └─... %>% ggplot(aes(y = items, x = items.b))
>   4. ├─ggplot2::ggplot(., aes(y = items, x = items.b))
>   5. ├─dplyr::mutate(., items = forcats::fct_reorder(items, items.b))
>   6. ├─dplyr:::mutate.data.frame(., items = forcats::fct_reorder(items, items.b))
>   7. │ └─dplyr:::mutate_cols(.data, dplyr_quosures(...), by)
>   8. │   ├─base::withCallingHandlers(...)
>   9. │   └─dplyr:::mutate_col(dots[[i]], data, mask, new_columns)
>  10. │     └─mask$eval_all_mutate(quo)
>  11. │       └─dplyr (local) eval()
>  12. ├─forcats::fct_reorder(items, items.b)
>  13. │ └─base::stopifnot(length(f) == length(.x))
>  14. └─base::.handleSimpleError(...)
>  15.   └─dplyr (local) h(simpleError(msg, call))
>  16.     └─rlang::abort(message, class = error_class, parent = parent, call = error_call)

**Comment by masurp** [comment]
Hi, 

yes, itempersonMap() will not work with graded response models (only with models that are based on binary data, e.g., 1PL, 2PL, 3PL, Rasch, etc.). The visualization function assumes that there is one difficulty parameter per item. But with graded response models, there are as many as there are answer options. Have to think about how to do this in a more comprehensive way. Sorry, that it doesn't work right now.

Best,
Philipp

**Comment by rameliaz** [comment]
Hi Phillip,

Ah right, thanks for explaining this...
