### ISSUE TITLE
`tracePlot` does not work with grm models

### ISSUE THREAD

**Issue by rameliaz** [masurp/ggmirt#6]
Hi Phillip,

I called `tracePlot` function to render occ curves for a grm model.

`narc_grm <- 'narc = 1-7'`
`fit_narc_grm <- mirt(data=narc, model=narc_grm, itemtype="graded", SE=T, verbose=F) `
`tracePlot(fit_narc_grm)`

...but this following error message appeared:

`Error in is(x, "SingleGroupClass") : object 'fitGraded' not found`

Any idea why that happened?

**Comment by ChingFanSheu** [comment]
I have encountered the same problem. See the error message below.
It seems that the program was looking for the object *fitGraded* when the object name I passed to
the *mod* argument is *grm* instead. 

***
Error in `ggmirt::tracePlot()`:
! object 'fitGraded' not found
Backtrace:
 1. ggmirt::tracePlot(mod = grm)
 7. mirt::probtrace(fitGraded, Theta = theta_range)
 8. methods::is(x, "SingleGroupClass")
Execution halted
***

**Comment by masurp** [comment]
Solve by @stats-matt. Thanks! ;)

**Comment by stats-matt** [comment]
Sure thing @masurp  - thanks for making a great package, it's incredibly helpful!

**Comment by rameliaz** [comment]
Thank you so much for resolving the issue, @stats-matt, and indeed @masurp for taking the time to create an amazingly helpful package!
